CREATE TABLE CLIENTES 
( 
 Cod_Cliente INT PRIMARY KEY,  
 Inicial INT,  
 Nome INT,  
 Sobrenome INT,  
 DDD INT,  
 Telefone INT,  
 Saldo INT,  
); 

CREATE TABLE FATURAS 
( 
 Num_Fatura INT PRIMARY KEY,  
 Data_Fatura INT,  
 idCLIENTES INT,  
); 

CREATE TABLE LINHAS 
( 
 Valor INT,  
 Unidades INT,  
 Num_Linha INT PRIMARY KEY,  
 idFATURAS INT,  
 idPRODUTOS INT,  
); 

CREATE TABLE PRODUTOS 
( 
 Cod_Produto INT PRIMARY KEY,  
 Descricao INT,  
 Data_Compra INT,  
 Quantidade INT,  
 Valor INT,  
 idFORNECEDORES INT,  
); 

CREATE TABLE FORNECEDORES 
( 
 Cod_Fornecedor INT PRIMARY KEY,  
 Nome INT,  
 Contato INT,  
 DDD INT,  
 Telefone INT,  
 Estado INT,  
); 

ALTER TABLE FATURAS ADD FOREIGN KEY(idCLIENTES) REFERENCES CLIENTES (idCLIENTES)
ALTER TABLE LINHAS ADD FOREIGN KEY(idFATURAS) REFERENCES FATURAS (idFATURAS)
ALTER TABLE LINHAS ADD FOREIGN KEY(idPRODUTOS) REFERENCES PRODUTOS (idPRODUTOS)
ALTER TABLE PRODUTOS ADD FOREIGN KEY(idFORNECEDORES) REFERENCES FORNECEDORES (idFORNECEDORES)
